language: c
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

matrix:
  include:
    - env: BUILD_TYPE=Debug ARCH_USER=ON
      os: osx
      osx_image: xcode8
      compiler: clang
    - env: BUILD_TYPE=Release ARCH_USER=ON
      os: osx
      osx_image: xcode8
      compiler: clang
    - env: CLANG_VERSION=3.6 BUILD_TYPE=Debug
      os: linux
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - gcc-5-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release
      os: linux
      addons: *clang36
    - env: CLANG_VERSION=3.7 BUILD_TYPE=Debug
      os: linux
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - gcc-5-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
    - env: CLANG_VERSION=3.7 BUILD_TYPE=Release
      os: linux
      addons: *clang37
    - env: CLANG_VERSION=3.8 BUILD_TYPE=Debug
      os: linux
      addons: &clang38
        apt:
          packages:
            - clang-3.8
            - gcc-5-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
    - env: CLANG_VERSION=3.8 BUILD_TYPE=Release
      os: linux
      addons: *clang38
    - env: CLANG_VERSION=3.9 BUILD_TYPE=Debug
      os: linux
      addons: &clang39
        apt:
          packages:
            - clang-3.9
            - gcc-5-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
    - env: CLANG_VERSION=3.9 BUILD_TYPE=Release
      os: linux
      addons: *clang39
    - env: GCC_VERSION=5 BUILD_TYPE=Debug
      os: linux
      addons: &gcc5
        apt:
          packages: gcc-5-multilib
          sources: *sources
    - env: GCC_VERSION=5 BUILD_TYPE=Release
      os: linux
      addons: *gcc5
    - env: GCC_VERSION=6 BUILD_TYPE=Debug
      os: linux
      addons: &gcc6
        apt:
          packages: gcc-6-multilib
          sources: *sources
    - env: GCC_VERSION=6 BUILD_TYPE=Release
      os: linux
      addons: *gcc6
    - env: GCC_VERSION=5 BUILD_TYPE=Debug ARCH_USER=ON
      os: linux
      addons: *gcc5
    - env: GCC_VERSION=6 BUILD_TYPE=Debug ARCH_USER=ON
      os: linux
      addons: *gcc6
    - env: GCC_VERSION=5 BUILD_TYPE=Release ARCH_USER=ON
      os: linux
      addons: *gcc5
    - env: GCC_VERSION=6 BUILD_TYPE=Release ARCH_USER=ON
      os: linux
      addons: *gcc6

install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
  - JOBS=1
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - "[ -z $ARCH_USER ] && ARCH_USER=OFF"
  - cmake . -Bout -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DARCH_USER=$ARCH_USER
  - cmake --build out -- -j$JOBS
